services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"